### PR TITLE
added code for ways to decode

### PR DESCRIPTION
**Pull request by find3rskeeper**
Added a file named dp_ways_to_decode containing 
1. The question at the top of the file.
2. Code solving the problem statement

Related issue #147 

Solved the question on interviewbit with all the test cases passing.

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (change which fixes an issue with the algorithm)

- [x] New Algorithm (non-breaking change which adds functionality)

- [ ] Documentation

## Checklist:
Go over all the following points, and put an `x` in all the boxes that apply.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [ ] My code follows the code style of this project.

- [ ] My change requires a change to the documentation.

- [x] I have updated the documentation accordingly.

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by find3rskeeper** [comment]
Added a solution to a problem I saw on interviewbit. Hope it helps. If anything is missing, please point me in the right direction. Created an issue already for the problem #147

**Comment by GnikDroy** [comment]
@find3rskeeper You seem to have forgotten to add the description.

**Comment by find3rskeeper** [comment]
How can I edit it now. New to the community, sorry

**Comment by GnikDroy** [comment]
In the above there are sections such as

## Description 

Please describe what changes you have made. ....


You are supposed to fill them up with your problem/solution. No problem if you are new to the community,

You can edit the comment by pressing on the three dots beside the comment.

**Comment by find3rskeeper** [comment]
@GnikDroy Updated the discription. Wanted to check if there is any code style documentation provided in the project.

**Pull request merged**
