### PR TITLE
Added Binary Search implementations in C, C++, Java and Python (Issue 42)

### PR DESCRIPTION
**Pull request by GnikDroy**
Here are some standard implementations of the Binary Search algorithm. 

As mentioned earlier, I have also added a README in the folder for easy information access. If this looks fine, we could do this for other algorithms as well.

### CODE REVIEW

**Comment by abhinav-adtechs** [comment]
Looks fine to me.

**Comment by GnikDroy** [comment]
That directory structure does not work with the readme file. It makes sense to organize code by the algorithms instead of the language. If I follow that method, I would need to copy the README file to 3 directories. Repetition of information. I propose to keep this structure.

**Comment by tstreamDOTh** [comment]
@GnikDroy Makes sense.  Can you document these things for others to follow as well? And also it will be great if you can create an issue to reformat other files as well to maintain uniformity.

**Comment by GnikDroy** [comment]
If two of my pending pull requests are accepted then I will work on this next.

**Pull request merged**
