### PR TITLE
BubbleSort Implementation in C++

### LINKED ISSUE #144: Implement BubbleSort in C++

### PR DESCRIPTION
**Pull request by 21RachitShukla**
Fixed #144

### CODE REVIEW

**Comment by GnikDroy** [comment]
@21RachitShukla Can you please fill in the required information. You can edit the above for changes.

**Comment by tstreamDOTh** [comment]
@21RachitShukla Try to adhere to Issue & PR templates next time

**Comment by 21RachitShukla** [comment]
I am unable to rename it C++ due to some reason!

**Comment by dushivani** [comment]
Can I do it if it's not done yet?

**Comment by GnikDroy** [comment]
@21RachitShukla I will help you out.

**Pull request merged**
